<?php

namespace Kuakao\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TAdminRepository extends EntityRepository
{
}
