<?php

namespace Kuakao\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TMemberRepositoryz
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TMemberRepository extends EntityRepository
{
}