<?php

namespace Kuakao\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Kuakao\AdminBundle\Entity\TSchool;

/**
 * TLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TSchoolRepository extends EntityRepository
{
    public function getAll($where = [], $order=['listorder'=>'ASC'])
    {
        $arr = array();

        $list = $this->findBy($where, $order);

        foreach ($list as $key => $val)
        {
            if (is_object($val))
            {
                $id     = $val->getId();
                $name   = $val->getName();
                $arr[$name] = $id;
            }
        }

        return $arr;
    }
}
