tattachment_index:
    path:     /
    defaults: { _controller: "KuakaoAdminBundle:TAttachment:index" }
    methods:  GET

tattachment_show:
    path:     /{id}/show
    defaults: { _controller: "KuakaoAdminBundle:TAttachment:show" }
    methods:  GET

tattachment_new:
    path:     /new
    defaults: { _controller: "KuakaoAdminBundle:TAttachment:new" }
    methods:  [GET, POST]

tattachment_edit:
    path:     /{id}/edit
    defaults: { _controller: "KuakaoAdminBundle:TAttachment:edit" }
    methods:  [GET, POST]

tattachment_delete:
    path:     /{id}/delete
    defaults: { _controller: "KuakaoAdminBundle:TAttachment:delete" }
    methods:  DELETE
